Upgrades to code and docs in makefile

diff --git a/pybuild/Makefile b/pybuild/Makefile
--- a/pybuild/Makefile
+++ b/pybuild/Makefile
@@ -1,17 +1,42 @@
 #
-# Makefile for pybuild23
+# Universal pybuild @ Jet Makefile w/git tagging support. If using the
+# versioneering package, no manual version bumping is required
 #
-# Usage:
-#   $ make <-- will build for Python2 by default
-#   $ make python2
-#   $ make python3
-#   $ make clean
-#   $ make rebuild
-#   $ make new REPO=https://github.com/someuser/someproject
+# Supported Targets:
+#  - all: Default target, build a python2 virtual environment in venv/
+#         Customize and commit venv/requirements.txt to your repo
+#         Activate as usual with source venv/bin/activate
+#  - python2: Same as `all` target
+#  - python3: Same as python2, except builds a python3 virtual environment
+#  - venv: Create a missing venv/ dir, you shouldn't ever need this
+#  - clean: Clean up the virtual environment without touching your code
+#           Everything in venv/ will be deleted except requirements.txt
+#  - rebuild: Equivalent to make clean && make
+#  - push: `git push`
+#  - pypirc: Dynamically/interactively creates a ~/.pypirc configured for
+#            user with Jet Artifactory. Only needed once on any given
+#            system, not per project, since pypirc is global to the user
+#            and not respected by virtualenv
+#  - release: Use git tag to automatically increment the version number.
+#             Next, use `python setup.py sdist upload` to publish to a
+#             PyPi repository (i.e. Artifactory) and let versioneer set
+#			  the versioning information into the dist automatically.
+#			  Finally, push code and tags (but do NOT)
+#	- freeze: Save the state of a deployed virtualenv, so it can be deployed
+#			  in a repeatable way if necessary.
 #
-# See the README.md for more details
+# Remember that PYTHON and PYTHON3 can be overridden on the command line
+# using `make PYTHON=/opt/my/python`. The same is true of the VENV_DIR
+# but there's really no reason to change the venv dir IMO.
 #
-
+# How does this work? This is all from pybuild, an old project of mine
+# and a friend, @ github.com/mzpqnxow/pybuild23. It is public and free
+# but copyrighted by me. It was not developed on Jet time and actually
+# predates Jet by quite a bit, though the repository has been created
+# and destroyed several times over the last few years
+#
+# - AG, 2018
+#
 ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 PYTHON2 = `which python2`
 PYTHON3 = `which python3`
@@ -20,23 +45,30 @@ RUNNING_USER = `whoami`
 VENV_DIR = $(ROOT_DIR)/venv/
 RM_RF := /bin/rm -rf
 PYBUILD := ./pybuild
+BUILD_FILES := build dist *.egg-info
 PROJECT_FILES := etc packages pybuild .gitignore examples/Makefile
 COPY_FILES := etc packages pybuild examples/Makefile venv
+PACKAGES := packages
+SYMLINKS := pip virtualenv easy_install
+PYPIRC := $(ROOT_DIR)/pypirc.template
 RELATIVE_ACTIVATE := pybuild/venv/bin/activate
 BACK_RELATIVE_ACTIVATE := ../activate
 
+CC := gcc
+
 all: python2
+
 
 python2: $(VENV_DIR) $(BACK_RELATIVE_ACTIVATE)
 	@echo "Executing pybuild (`basename $(PYBUILD)` -p $(PYTHON) $(VENV_DIR))"
 	@cd $(ROOT_DIR) && $(PYBUILD) -p $(PYTHON) $(VENV_DIR)
-
+ 
 python3: $(VENV_DIR) $(BACK_RELATIVE_ACTIVATE)
 	@echo "Executing pybuild (`basename $(PYBUILD)` -p $(PYTHON3) $(VENV_DIR))"
 	@cd $(ROOT_DIR) && $(PYBUILD) -p $(PYTHON3) --python3 $(VENV_DIR)
 
 $(BACK_RELATIVE_ACTIVATE):
-	@cd $(ROOT_DIR) && ln -sf $(RELATIVE_ACTIVATE) $(BACK_RELATIVE_ACTIVATE)
+       @cd $(ROOT_DIR) && ln -sf $(RELATIVE_ACTIVATE) $(BACK_RELATIVE_ACTIVATE)
 
 $(VENV_DIR):
 	@echo "----"
@@ -44,39 +76,68 @@ $(VENV_DIR):
 	@echo "----"
 	@mkdir -p $(VENV_DIR)
 
-check_root:
-	@[ $(RUNNING_USER) != "root" ] || (echo Disallowing clean as root user; /bin/false)
-
-clean: check_root
-	@cd $(ROOT_DIR) && TMPFILE=`mktemp` && \
-	  cp venv/requirements.txt $$TMPFILE && \
-          rm -rf $(VENV_DIR) && \
-          mkdir $(VENV_DIR) && \
-          mv $$TMPFILE $(VENV_DIR)/requirements.txt && \
-          rm -rf ~/.cache/pip && \
-          rm -f ../activate
-
-
-rebuild: clean python2
-rebuild2: rebuild
-rebuild3: clean python3
-
 #
-# Install pybuild into an existing git repository so it can be used to
-# build your venv in that project. Use this after you create a new
-# project and it will set it up for use with a venv. You probably
-# don't want to use this on a project that already has files in it
-# because they could get clobbered. The list of files that will be
-# clobbered is in $(PROJECT_FILES)
+# Using versioneer to automate all of this, your current git tag will be
+# incremented by the patch (1.0.0->1.0.1) if you just use `make release`
 #
-# Usage example:
-#   $ make new REPO=ssh://github.com/yourname/your_existing_empty_repo
 #
-# This will clone the repo and install the pybuild files into the root
-# of the repo, commit the changes, and push
+# By default, make release will:
+#  - tag your current branch
+#      $ make release bump=major
+#      $ make release bump=minor
+#      $ make release
+#  - Publish your Python package to your PyPi repository with the new tag
+#  - Perform a git push on any committed changes you have
+#  - Perform a git push --tags to add the new tag to git
 #
+#
+release:
+	$(eval v := $(shell git describe --tags --abbrev=0 | sed -Ee 's/^v|-.*//'))
+ifeq ($(bump), major)
+	$(eval f := 1)
+else ifeq ($(bump), minor)
+	$(eval f := 2)
+else
+	$(eval f := 3)
+endif
+	git tag `echo $(v) | awk -F. -v OFS=. -v f=$(f) '{ $$f++ } 1'`
+	python setup.py sdist upload -r local
+	git commit CHANGELOG.md -m "Bumped to version `echo $(v) | \
+	  awk -F. -v OFS=. -v f=$(f) '{ $$f++ } 1'`"
+	git push
+	git push --tags
+
+push:
+	git push
+
+freeze:
+	$(PYBUILD) --freeze $(VENV_DIR) 
+
+pypirc:
+	@echo '-------- Jet PyPirc Installation --------'
+	echo ''
+	echo 'Follow the prompts to install a ~/.pypirc file that allows you to publish to Jet Artifactory'
+	echo 'WARN: This is a global configuration file for your username ($$USER)'
+	echo 'NOTICE: Any existing ~/.pypirc will be backed up in ~/.pypirc.bak.*'
+	echo '-------- Jet PyPirc Crdentials --------'
+	echo 'Please enter your credentials and a PyPirc file will be created'
+	echo 'SECURITY: The file will be stored mode 0600 in ~/.pypirc, private from other users :>'
+	echo
+	cp ~/.pypirc ~/.pypirc.bak.$(date +%s) && \
+	echo -n 'Please enter JET.local username (without @jet.com): ' && \
+	read user && \
+	echo -n 'Please enter JET.local password: ' && \
+	read pass && \
+	sed \
+          -e "s/%%USER%%/$$user/" \
+          -e "s/%%PASS%%/$$pass/" \
+          $(PYPIRC) > ~/.pypirc && \
+          chmod 600 ~/.pypirc && \
+          echo "Installation complete, `make publish` should now work for you" 
+
 new:
-	set -e; \
+       set -e; \
+       	cd $(ROOT_DIR) && \
          export REPO_STRIPPED=$$(echo $(REPO) | sed -e 's|\.git||') && \
          export REPO_BASENAME=$$(basename $$REPO_STRIPPED) && \
          git clone $$REPO_STRIPPED && \
@@ -99,8 +160,30 @@ new:
          echo "    $ git log" && \
          echo
 
-test:
-	echo $(ROOT_DIR)
-	echo $(PROJECT_FILES)
+check_root:
+	@[ $(RUNNING_USER) != "root" ] || (echo Disallowing clean as root user; /bin/false)
 
-.PHONY:	python2 python3 test new copy rebuild clean check_root
+
+clean: check_root
+	@cd $(ROOT_DIR) && TMPDIR=`mktemp -d` && \
+	  cp venv/*requirements*.txt $$TMPDIR/ && \
+          rm -rf $(VENV_DIR) && \
+          mkdir $(VENV_DIR) && \
+          mv $$TMPDIR/*requirements*.txt $(VENV_DIR)/ && \
+          rm -f $(PACKAGES)/{$(SYMLINKS)} && \
+          rm -rf $(BUILD_FILES) && \
+          rm -rf $$TMPDIR && \
+          rm -f $(BACK_RELATIVE_ACTIVATE)
+
+rebuild: distclean python2
+
+rebuild2: rebuild
+
+rebuild3: distclean clean python3
+
+distclean:
+	@rm -rf $(BUILD_FILES)
+
+rebuild: clean all
+
+.PHONY:	python2 python3 rebuild rebuild2 rebuild3 clean pypirc release push distclean check_root
